# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
r:
  - oldrel
  - release
  - devel
cache: packages
bioc_packages:
  - edgeR
  - limma
r_packages:
  - covr
r_github_packages:
  - cb4ds/DGEobj.utils@cran
after_success:
  - Rscript -e 'library(covr); codecov(quiet = FALSE)'
latex: false

